openapi: '3.0.2'
info:
  title: SewaBuku
  description: Part of Alterra Academy Project
  termsOfService: http://example.com/terms/
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: '1.0'
servers:
  - description: Server Sewabuku API
    url: https://{environment}.sewabuku.id/api/v1
    variables:
      environment:
        default: dev
        enum:
          - dev
          - prod
tags:
  - name: Users
    description: User control
  - name: Books
    description: Book data management
  - name: Accounts
    description: All about deposit transaction
paths:
  ####################################
  #  USERS
  ####################################
  /users/register:
    post:
      tags:
        - Users
      description: Register user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UsersSchema'
      responses:
        '200':
          $ref: '#/components/responses/registerSuccess'
        '400':
          $ref: '#/components/responses/registerFailed'
  /users/login:
    post:
      tags:
        - Users
      description: Login user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: bangtegar@gmail.com
                password:
                  type: string
                  example: iniPaswordAing123
      responses:
        '200':
          $ref: '#/components/responses/loginSuccess'
        '400':
          $ref: '#/components/responses/loginFailed'
  /users/profile:
    get:
      tags:
        - Users
      responses:
        '200':
          $ref: '#/components/responses/getUserProfileSuccess'
        '400':
          $ref: '#/components/responses/getUserProfileFailed'
    post:
      tags:
        - Users
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UsersSchema'
      responses:
        '200':
          $ref: '#/components/responses/editUserProfileSuccess'
        '400':
          $ref: '#/components/responses/editUserPasswordFailed'
  /users/change-password:
    post:
      tags:
        - Users
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                oldPassword:
                  type: string
                  example: iniPaswordAing123
                newPassword:
                  type: string
                  example: hesoyam99
      responses:
        '200':
          $ref: '#/components/responses/editUserPasswordSuccess'
        '400':
          $ref: '#/components/responses/editUserPasswordFailed'
  ####################################
  #  BOOKS
  ####################################
  /books:
    post:
      tags:
        - Books
      description: Insert new book
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                #ini body request book
      responses:
        '200':
          $ref: '#/components/responses/getUserProfileSuccess'
        '400':
          $ref: '#/components/responses/getUserProfileFailed'
    get:
      tags:
        - Books
      description: Get all books
      responses:
        '200':
          $ref: '#/components/responses/getUserProfileSuccess'
        '400':
          $ref: '#/components/responses/getUserProfileFailed'
    put:
      tags:
        - Books
      description: Update book
      responses:
        '200':
          $ref: '#/components/responses/getUserProfileSuccess'
        '400':
          $ref: '#/components/responses/getUserProfileFailed'
    delete:
      tags:
        - Books
      description: Delete book
      responses:
        '200':
          $ref: '#/components/responses/getUserProfileSuccess'
        '400':
          $ref: '#/components/responses/getUserProfileFailed'


  #
  #
  ####################################
  #  ACCOUNTS
  ####################################
  /account:
    get:
      tags:
        - Accounts
      description: return all transaction history
      responses:
        '200':
          description: OK
    post:
      tags:
        - Accounts
      description: make deposit
      responses:
        '200':
          description: OK

components:
  responses:
    #==================================#
    #    RESPONSE REGISTER USER
    #==================================#
    registerSuccess:
      description: register success
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: string
                example: success
              message:
                type: string
                example: Register Success
    registerFailed:
      description: register failed
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: string
                example: fail
              message:
                type: string
                example: Register Failed
    #==================================#
    #    RESPONSE LOGIN USER
    #==================================#
    loginSuccess:
      description: login success
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: string
                example: success
              message:
                type: string
                example: Login Success
              data:
                type: object
                properties:
                  token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJ1c2VySWQiOjExfQ.YQ47sxFkIfbDVyQ5o6ix38w4BYxnNOPG3F5isqkyyv8
    loginFailed:
      description: login failed
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: string
                example: fail
              message:
                type: string
                example: Login Failed
    #==================================#
    #    RESPONSE GET USER PROFILE
    #==================================#
    getUserProfileSuccess:
      description: success get user profile
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: string
                example: success
              message:
                type: string
                example: Success Get User Profile
    getUserProfileFailed:
      description: fail to get user profile
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: string
                example: fail
              message:
                type: string
                example: Fail to Get User Profile
    #==================================#
    #    RESPONSE EDIT USER PROFILE
    #==================================#
    editUserProfileSuccess:
      description: success change user profile
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: string
                example: success
              message:
                type: string
                example: Success Change User Profile
    editUserProfileFailed:
      description: fail to change user profile
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: string
                example: fail
              message:
                type: string
                example: Fail to Change User Profile
    #==================================#
    #    RESPONSE EDIT USER PASSWORD
    #==================================#
    editUserPasswordSuccess:
      description: success change password
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: string
                example: success
              message:
                type: string
                example: Success Change Password
    editUserPasswordFailed:
      description: fail to change password
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: string
                example: fail
              message:
                type: string
                example: Fail to Change Password





  #----------------------------------#
  #    SCHEMAS
  #----------------------------------#

