name: Deploy to EC2 (Production)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to EC2 using SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /home/ec2-user/draf-sewabuku
          git pull origin main
          docker stop sewabukuContainer
          docker rm sewabukuContainer
          docker build -t sewabuku:latest .
          docker run -d -p 80:8080 --name sewabukuContainer sewabuku:latest
